export const PROJECTS_FETCHED = 'project.PROJECTS_FETCHED';
export const PROJECT_SURVEYS_FETCHED = 'project.PROJECT_SURVEYS_FETCHED';
export const SURVEY_QUESTIONS_FETCHED = 'project.SURVEY_QUESTIONS_FETCHED';
